import os
import re

def fix_initial_schema():
    path = "backend/alembic/versions/22596d6d3ef1_initial_schema.py"
    with open(path, "r") as f:
        content = f.read()

    upgrade_code = """    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(), nullable=True),
        sa.Column('prenom', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('mdp', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nom'), 'users', ['nom'], unique=False)
    op.create_index(op.f('ix_users_prenom'), 'users', ['prenom'], unique=False)

    op.create_table('societe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('logo', sa.String(), nullable=True),
        sa.Column('nom', sa.String(), nullable=False),
        sa.Column('adresse', sa.Text(), nullable=True),
        sa.Column('code_postal', sa.String(), nullable=True),
        sa.Column('ville', sa.String(), nullable=True),
        sa.Column('telephone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('siret', sa.String(), nullable=True),
        sa.Column('iban', sa.String(), nullable=True),
        sa.Column('bic', sa.String(), nullable=True),
        sa.Column('nom_banque', sa.String(), nullable=True),
        sa.Column('capital_social', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('rcs', sa.String(), nullable=True),
        sa.Column('tva_intracommunautaire', sa.String(), nullable=True),
        sa.Column('forme_juridique', sa.String(), nullable=True),
        sa.Column('tva_defaut', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('dernier_numero_facture', sa.String(), nullable=True),
        sa.Column('objectif_mensuel_ca', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('texte_pied_page', sa.Text(), nullable=True),
        sa.Column('id_user', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_societe_id'), 'societe', ['id'], unique=False)
    op.create_index(op.f('ix_societe_nom'), 'societe', ['nom'], unique=False)"""

    downgrade_code = """    op.drop_index(op.f('ix_societe_nom'), table_name='societe')
    op.drop_index(op.f('ix_societe_id'), table_name='societe')
    op.drop_table('societe')
    op.drop_index(op.f('ix_users_prenom'), table_name='users')
    op.drop_index(op.f('ix_users_nom'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')"""

    content = re.sub(r'def upgrade\(\) -> None:\s*# ### commands auto generated by Alembic - please adjust! ###\s*pass', f'def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n{upgrade_code}', content)
    content = re.sub(r'def downgrade\(\) -> None:\s*# ### commands auto generated by Alembic - please adjust! ###\s*pass', f'def downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n{downgrade_code}', content)

    with open(path, "w") as f:
        f.write(content)

def fix_client_migration():
    path = "backend/alembic/versions/fba93a9e153f_add_client_table.py"
    with open(path, "r") as f:
        content = f.read()
    
    upgrade_code = """
    op.create_table('devis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_devis', sa.Date(), nullable=False),
        sa.Column('numero_devis', sa.String(), nullable=False),
        sa.Column('titre_document_pdf', sa.String(), nullable=False),
        sa.Column('objet_devis', sa.String(), nullable=True),
        sa.Column('sous_total_ht', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('total_tva', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('total_ttc', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('nb_jours_validite', sa.Integer(), server_default='30', nullable=False),
        sa.Column('conditions_particulieres', sa.Text(), nullable=True),
        sa.Column('statut', sa.String(), server_default='brouillon', nullable=False),
        sa.Column('signature', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('id_client', sa.Integer(), nullable=False),
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_id'), 'devis', ['id'], unique=False)
    op.create_index(op.f('ix_devis_numero_devis'), 'devis', ['numero_devis'], unique=True)

    op.create_table('factures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_facture', sa.Date(), nullable=False),
        sa.Column('numero_facture', sa.String(), nullable=False),
        sa.Column('titre_document_pdf', sa.String(), nullable=False),
        sa.Column('objet_facture', sa.String(), nullable=True),
        sa.Column('sous_total_ht', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('total_tva', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('total_ttc', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
        sa.Column('nb_jours_echeance', sa.Integer(), server_default='30', nullable=False),
        sa.Column('date_echeance', sa.Date(), nullable=True),
        sa.Column('statut', sa.String(), server_default='brouillon', nullable=False),
        sa.Column('est_payee', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('id_facture_source', sa.Integer(), nullable=True),
        sa.Column('conditions_particulieres', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('id_client', sa.Integer(), nullable=False),
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.Column('id_devis', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['id_devis'], ['devis.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['id_facture_source'], ['factures.id'], ),
        sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_numero_facture'), 'factures', ['numero_facture'], unique=True)

    op.create_table('lignes_devis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('prix_unite_ht', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('taux_tva', sa.Numeric(precision=4, scale=1), server_default='20.0', nullable=False),
        sa.Column('total_ht', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('id_devis', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_devis'], ['devis.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_devis_id'), 'lignes_devis', ['id'], unique=False)

    op.create_table('lignes_facture',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('prix_unite_ht', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('taux_tva', sa.Numeric(precision=4, scale=1), server_default='20.0', nullable=False),
        sa.Column('total_ht', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('id_facture', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_facture'], ['factures.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_facture_id'), 'lignes_facture', ['id'], unique=False)"""
    
    content = content.replace("op.create_index(op.f('ix_clients_nom'), 'clients', ['nom'], unique=False)\n    # ### end Alembic commands ###", "op.create_index(op.f('ix_clients_nom'), 'clients', ['nom'], unique=False)\n" + upgrade_code + "\n    # ### end Alembic commands ###")
    
    with open(path, "w") as f:
        f.write(content)

fix_initial_schema()
fix_client_migration()
