"""add_date_inscription_to_users

Revision ID: 1f7d9ed83f48
Revises: d3338284a73d
Create Date: 2026-08-07 11:23:27.503422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7d9ed83f48'
down_revision: Union[str, None] = 'd3338284a73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_inscription', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_inscription')
    # ### end Alembic commands ###
