"""add remote signature and payment reminders

Revision ID: 21d35f015564
Revises: a7c9d2e4f801
Create Date: 2026-08-30 14:08:01.890813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d35f015564'
down_revision: Union[str, None] = 'a7c9d2e4f801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relances_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_facture', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('jours_de_retard', sa.Integer(), server_default='0', nullable=False),
    sa.Column('destinataire', sa.String(), nullable=False),
    sa.Column('envoyee_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('automatique', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['id_facture'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_facture', 'niveau', name='uq_relance_facture_niveau')
    )
    op.create_index(op.f('ix_relances_facture_id'), 'relances_facture', ['id'], unique=False)
    op.create_index(op.f('ix_relances_facture_id_facture'), 'relances_facture', ['id_facture'], unique=False)
    op.add_column('devis', sa.Column('signature_token', sa.String(), nullable=True))
    op.add_column('devis', sa.Column('signature_token_expire_le', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devis', sa.Column('signature_nom', sa.String(), nullable=True))
    op.add_column('devis', sa.Column('signature_email', sa.String(), nullable=True))
    op.add_column('devis', sa.Column('signature_le', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devis', sa.Column('signature_ip', sa.String(), nullable=True))
    op.add_column('devis', sa.Column('signature_user_agent', sa.Text(), nullable=True))
    op.add_column('devis', sa.Column('signature_empreinte', sa.String(), nullable=True))
    op.create_index(op.f('ix_devis_signature_token'), 'devis', ['signature_token'], unique=True)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.add_column('societe', sa.Column('relances_actives', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('societe', sa.Column('relances_jours', sa.String(), server_default='3,10,21', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('societe', 'relances_jours')
    op.drop_column('societe', 'relances_actives')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_devis_signature_token'), table_name='devis')
    op.drop_column('devis', 'signature_empreinte')
    op.drop_column('devis', 'signature_user_agent')
    op.drop_column('devis', 'signature_ip')
    op.drop_column('devis', 'signature_le')
    op.drop_column('devis', 'signature_email')
    op.drop_column('devis', 'signature_nom')
    op.drop_column('devis', 'signature_token_expire_le')
    op.drop_column('devis', 'signature_token')
    op.drop_index(op.f('ix_relances_facture_id_facture'), table_name='relances_facture')
    op.drop_index(op.f('ix_relances_facture_id'), table_name='relances_facture')
    op.drop_table('relances_facture')
    # ### end Alembic commands ###
