"""Initial schema

Revision ID: 22596d6d3ef1
Revises: 
Create Date: 2026-04-01 15:01:47.954038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22596d6d3ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nom', sa.String(), nullable=True),
        sa.Column('prenom', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('mdp', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nom'), 'users', ['nom'], unique=False)
    op.create_index(op.f('ix_users_prenom'), 'users', ['prenom'], unique=False)

    op.create_table('societe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('logo', sa.String(), nullable=True),
        sa.Column('nom', sa.String(), nullable=False),
        sa.Column('adresse', sa.Text(), nullable=True),
        sa.Column('code_postal', sa.String(), nullable=True),
        sa.Column('ville', sa.String(), nullable=True),
        sa.Column('telephone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('siret', sa.String(), nullable=True),
        sa.Column('iban', sa.String(), nullable=True),
        sa.Column('bic', sa.String(), nullable=True),
        sa.Column('nom_banque', sa.String(), nullable=True),
        sa.Column('capital_social', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('rcs', sa.String(), nullable=True),
        sa.Column('tva_intracommunautaire', sa.String(), nullable=True),
        sa.Column('forme_juridique', sa.String(), nullable=True),
        sa.Column('tva_defaut', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('dernier_numero_facture', sa.String(), nullable=True),
        sa.Column('objectif_mensuel_ca', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('texte_pied_page', sa.Text(), nullable=True),
        sa.Column('id_user', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_societe_id'), 'societe', ['id'], unique=False)
    op.create_index(op.f('ix_societe_nom'), 'societe', ['nom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_societe_nom'), table_name='societe')
    op.drop_index(op.f('ix_societe_id'), table_name='societe')
    op.drop_table('societe')
    op.drop_index(op.f('ix_users_prenom'), table_name='users')
    op.drop_index(op.f('ix_users_nom'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
