"""add photos to rapports

Revision ID: 3220a1468f5f
Revises: 42f809c8c3ea
Create Date: 2026-04-07 16:59:59.089596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3220a1468f5f'
down_revision: Union[str, None] = '42f809c8c3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapports', sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapports', 'photos')
    # ### end Alembic commands ###
