"""remove id_rapport from devis

Revision ID: 4da588203cc9
Revises: b8c9d0e1f2a3
Create Date: 2026-08-09 10:52:59.572440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da588203cc9'
down_revision: Union[str, None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis', 'id_rapport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('id_rapport', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_devis_rapports', 'devis', 'rapports', ['id_rapport'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
