"""add est_acompte to facture

Revision ID: 8338067ca026
Revises: 4da588203cc9
Create Date: 2026-08-09 10:59:53.761021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8338067ca026'
down_revision: Union[str, None] = '4da588203cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('est_acompte', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'est_acompte')
    # ### end Alembic commands ###
