"""Add Rapport table

Revision ID: 96b0f0ae4638
Revises: fba93a9e153f
Create Date: 2026-04-05 20:52:23.450962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b0f0ae4638'
down_revision: Union[str, None] = 'fba93a9e153f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_intervention', sa.Date(), nullable=False),
    sa.Column('titre_document_pdf', sa.String(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('url_pdf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapports_id'), 'rapports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rapports_id'), table_name='rapports')
    op.drop_table('rapports')
    # ### end Alembic commands ###
