"""make_user_password_nullable

Revision ID: a62de430368b
Revises: 3220a1468f5f
Create Date: 2026-04-07 17:30:33.351752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62de430368b'
down_revision: Union[str, None] = '3220a1468f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mdp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mdp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
