"""add_est_avoir_to_factures

Revision ID: b73de430368b
Revises: a62de430368b
Create Date: 2026-04-25 21:58:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73de430368b'
down_revision: Union[str, None] = 'a62de430368b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('est_avoir', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('factures', sa.Column('id_facture_source', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factures', 'factures', ['id_facture_source'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factures', type_='foreignkey')
    op.drop_column('factures', 'id_facture_source')
    op.drop_column('factures', 'est_avoir')
    # ### end Alembic commands ###
