"""add onboarding_draft to user

Revision ID: d3338284a73d
Revises: cb6cab307674
Create Date: 2026-08-05 16:15:35.034970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3338284a73d'
down_revision: Union[str, None] = 'cb6cab307674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_draft', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_draft')
    # ### end Alembic commands ###
