"""add active_societe_id

Revision ID: e1facc9ad420
Revises: 8338067ca026
Create Date: 2026-08-09 16:09:57.306551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1facc9ad420'
down_revision: Union[str, None] = '8338067ca026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_societe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'societe', ['active_societe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_societe_id')
    # ### end Alembic commands ###
